# Generated by Django 5.1.4 on 2024-12-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='first',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='Flights',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last',
        ),
        migrations.AddField(
            model_name='passenger',
            name='flights',
            field=models.ManyToManyField(related_name='passengers', to='flights.flight'),
        ),
    ]
